#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Digiwin custom Kyuubi image, based on the in-cluster spark-iceberg image.
#
# Differences from docker/Dockerfile:
#   - hardcoded FROM (old docker on build nodes does not support ARG before FROM)
#   - no apt layer (ctr export/docker load round-trip breaks apt keyrings, and
#     tini/krb5/procps are not required for Kyuubi)
#   - also copies the JDBC engine (official Dockerfile only copies Spark engine)
#
# Build (from the unpacked binary tarball directory):
#   1. put the mysql driver into the jdbc engine dir first:
#      wget -P externals/engines/jdbc/ \
#        https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar
#   2. docker build -f docker/Dockerfile.digiwin -t kyuubi:1.11.1-digiwin .

FROM spark-iceberg:3.5.8

USER root

ENV KYUUBI_HOME=/opt/kyuubi
ENV KYUUBI_LOG_DIR=${KYUUBI_HOME}/logs
ENV KYUUBI_PID_DIR=${KYUUBI_HOME}/pid
ENV KYUUBI_WORK_DIR_ROOT=${KYUUBI_HOME}/work
ENV SPARK_HOME=/opt/spark

RUN set -ex && \
    ln -snf /bin/bash /bin/sh && \
    useradd -u 10009 -g root kyuubi -d /home/kyuubi -m && \
    mkdir -p ${KYUUBI_HOME} ${KYUUBI_LOG_DIR} ${KYUUBI_PID_DIR} ${KYUUBI_WORK_DIR_ROOT}

COPY LICENSE NOTICE RELEASE ${KYUUBI_HOME}/
COPY bin ${KYUUBI_HOME}/bin
COPY jars ${KYUUBI_HOME}/jars
COPY beeline-jars ${KYUUBI_HOME}/beeline-jars
COPY web-ui ${KYUUBI_HOME}/web-ui
COPY externals/engines/spark ${KYUUBI_HOME}/externals/engines/spark
COPY externals/engines/jdbc ${KYUUBI_HOME}/externals/engines/jdbc

WORKDIR ${KYUUBI_HOME}
RUN chown -R kyuubi:root ${KYUUBI_HOME} && \
    chmod ug+rw -R ${KYUUBI_HOME} && \
    chmod a+rwx -R ${KYUUBI_WORK_DIR_ROOT}

CMD [ "./bin/kyuubi", "run" ]

USER 10009
